entervuapp/sprint-2

package-lock.json
src/app/app.component.html
src/app/app.component.ts
src/app/commons/components/contact-us/contact-us.component.html
src/app/commons/directives/highlight-required-fields/highlight-required-fields.directive.ts
src/app/commons/services/can-deactivate-guard/can-deactivate-guard.service.spec.ts
src/app/commons/services/can-deactivate-guard/can-deactivate-guard.service.ts
src/app/commons/services/local-storage/local-storage.service.spec.ts
src/app/commons/services/local-storage/local-storage.service.ts
src/app/commons/services/manage-header/manage-header.service.spec.ts
src/app/commons/services/manage-header/manage-header.service.ts
src/app/commons/services/services.module copy.ts
src/app/commons/services/window-ref/window-ref.service.spec.ts
src/app/commons/services/window-ref/window-ref.service.ts
src/app/commons/typings/typings.ts
src/app/commons/utils/object-utils.ts
src/app/resources/individual/dashboard-individual/dashboard-individual.component.ts
src/app/resources/main-screen/main-screen.component.html
src/app/resources/main-screen/main-screen.component.ts
src/app/resources/organization/dashboard-organization/dashboard-organization.component.ts
src/app/resources/qa/qa-sample/qa-sample.component.html
src/app/resources/qa/qa-sample/qa-sample.component.spec.ts
src/app/resources/qa/qa-sample/qa-sample.component.ts
src/app/resources/qa/qa.module.ts
src/app/resources/resources.module.ts

header changes

---

src/app/app-routing.module.ts
src/app/app.component.ts
src/app/app.module.ts
src/app/commons/components/login-form/login-form.component.html
src/app/commons/components/login-form/login-form.component.ts
src/app/commons/components/login-form/login-form/login-form.service.spec.ts
src/app/commons/components/login-form/login-form/login-form.service.ts
src/app/commons/constants/api-urls.ts
src/app/commons/constants/route-url-path.constants.ts
src/app/resources/individual/individual-routing.module.ts
src/app/resources/main-screen/main-screen.component.html
src/app/resources/organization/dashboard-organization/dashboard-organization.component.html
src/app/resources/organization/registration-organization/registration-organization.component.ts
src/polyfills.ts

singinandsingup

---

src/app/app.module.ts
src/app/commons/components/components.module.ts
src/app/commons/components/date-input-field/date-input-field.component.html
src/app/commons/components/date-input-field/date-input-field.component.spec.ts
src/app/commons/components/date-input-field/date-input-field.component.ts
src/app/commons/components/display-date/display-date.component.html
src/app/commons/components/display-date/display-date.component.spec.ts
src/app/commons/components/display-date/display-date.component.ts
src/app/commons/components/error-message/error-message.component.html
src/app/commons/components/error-message/error-message.component.ts
src/app/commons/components/modals/confirm-popup/confirm-popup.component.html
src/app/commons/components/time-input-field/time-input-field.component.html
src/app/commons/components/time-input-field/time-input-field.component.spec.ts
src/app/commons/components/time-input-field/time-input-field.component.ts
src/app/commons/directives/highlight-required-fields/highlight-required-fields.directive.ts
src/app/commons/utils/object-utils.ts
src/app/resources/organization/manage-events/manage-events.component.html
src/app/resources/organization/manage-events/manage-events.component.ts

Time field component added with validations

added time field component

---

src/app/app.module.ts
src/app/commons/components/display-date/display-date.component.html
src/app/commons/components/display-date/display-date.component.ts
src/app/commons/components/time-input-field/time-input-field.component.ts
src/app/commons/pipes/pipes.module.ts
src/app/resources/organization/manage-events/manage-events.component.html
src/app/resources/organization/manage-events/manage-events.component.ts

addedDisplayDateComponent

---

src/app/app.component.html
src/app/commons/components/loading-spinner/loading-spinner.component.html
src/app/commons/components/loading-spinner/loading-spinner.component.ts
src/app/commons/services/loader/loader.service.ts
src/app/commons/services/loading-interceptor/loading-interceptor.service.ts
src/sass/_common.scss

loader service integrated

---

src/app/commons/components/time-input-field/time-input-field.component.ts
src/app/commons/directives/numbers-only/numbers-only.directive.ts
src/app/resources/organization/manage-events/manage-events.component.html
src/app/resources/organization/manage-events/manage-events.component.ts

fixed events page

---

db.json
src/app/app.component.html
src/app/commons/components/time-input-field/time-input-field.component.ts
src/app/commons/constants/api-urls.ts
src/app/commons/typings/typings.ts
src/app/resources/organization/manage-events/manage-events.component.html
src/app/resources/organization/manage-events/manage-events.component.ts
src/app/resources/organization/manage-events/manage-events/manage-events.service.spec.ts
src/app/resources/organization/manage-events/manage-events/manage-events.service.ts

Events service integration

---

db.json
src/app/resources/organization/manage-events/manage-events.component.ts

fixed events skill issue

---

db.json
src/app/commons/components/save-cancel-buttons/save-cancel-buttons.component.html
src/app/commons/components/save-cancel-buttons/save-cancel-buttons.component.scss
src/app/commons/components/save-cancel-buttons/save-cancel-buttons.component.ts
src/app/resources/organization/manage-events/manage-events.component.html
src/app/resources/organization/manage-events/manage-events.component.scss

added class in save cancel component

added class in save cancel component

---

db.json
package-lock.json
package.json
src/app/app-routing.module.ts
src/app/commons/components/login-form/login-form.component.html
src/app/commons/components/login-form/login-form.component.ts
src/app/commons/components/save-cancel-buttons/save-cancel-buttons.component.html
src/app/commons/constants/api-urls.ts
src/app/resources/organization/manage-candidates/manage-candidates.component.html
src/app/resources/organization/manage-candidates/manage-candidates.component.ts
src/app/resources/organization/manage-candidates/manage-candidates/manage-candidate.service.spec.ts
src/app/resources/organization/manage-candidates/manage-candidates/manage-candidate.service.ts
src/app/resources/organization/manage-events/manage-events.component.html
src/app/resources/organization/manage-events/manage-events.component.ts
src/app/resources/organization/organization-routing.module.ts
src/app/resources/organization/registration-organization/registration-organization.component.html

add candidate service integration

add candidate service integration

---

db.json
src/app/app-routing.module.ts
src/app/app.component.ts
src/app/commons/components/header/header.component.ts
src/app/commons/constants/route-url-path.constants.ts
src/app/commons/constants/shared.constants.ts
src/app/resources/admin/admin-dashboard/admin-dashboard.component.html
src/app/resources/admin/admin-dashboard/admin-dashboard.component.spec.ts
src/app/resources/admin/admin-dashboard/admin-dashboard.component.ts
src/app/resources/admin/admin-routing.module.ts
src/app/resources/admin/admin.module.ts
src/app/resources/organization/manage-candidates/manage-candidates.component.html
src/app/resources/organization/manage-candidates/manage-candidates.component.ts
src/app/resources/organization/manage-events/manage-events.component.html
src/app/resources/organization/manage-events/manage-events.component.ts
src/app/resources/organization/registration-organization/registration-organization.component.ts
src/app/resources/resources.module.ts

add candidate changes

---

src/app/commons/components/auto-complete/auto-complete.component.html
src/app/commons/components/auto-complete/auto-complete.component.ts
src/app/commons/components/carousel/carousel.component.ts
src/app/resources/individual/dashboard-individual/dashboard-individual.component.html

autoComplete changes

---

db.json
src/app/commons/components/error-message/error-message.component.html
src/app/commons/utils/object-utils.ts
src/app/resources/organization/manage-candidates/manage-candidates.component.html
src/app/resources/organization/manage-candidates/manage-candidates.component.ts
src/app/resources/organization/manage-events/manage-events.component.html
src/app/resources/organization/manage-events/manage-events.component.ts

event autcomplete changes

---

db.json
src/app/commons/typings/typings.ts
src/app/resources/organization/manage-candidates/manage-candidates.component.html
src/app/resources/organization/manage-candidates/manage-candidates.component.ts
src/app/resources/organization/manage-events/manage-events.component.html
src/app/resources/organization/manage-events/manage-events.component.ts

add candidate skills updated

---

src/app/commons/constants/font-awesome-icons.ts
src/app/resources/admin/admin-dashboard/admin-dashboard.component.css
src/app/resources/admin/admin-dashboard/admin-dashboard.component.html
src/app/resources/admin/admin-dashboard/admin-dashboard.component.ts

admin module added

---

db.json
src/app/resources/admin/manage-skills/manage-skills.component.ts

Event autocomplete change

---

comming-soon.txt
db.json
src/app/resources/organization/manage-candidates/manage-candidates.component.html
src/app/resources/organization/manage-events/manage-events.component.html
src/app/resources/organization/manage-events/manage-events.component.ts

events skill validations added

events skill validations

---

src/app/app.component.ts
src/app/commons/components/auto-complete/auto-complete.component.ts
src/app/commons/components/autocomplete/skills-autocomplete/skills-autocomplete.component.ts
src/app/commons/components/login-form/login-form.component.ts
src/app/resources/admin/manage-skills/manage-skills.component.ts
src/app/resources/organization/registration-organization/registration-organization.component.ts

added subscriptions on destroy

added subscriptions on destroy

---

db.json
src/app/resources/admin/manage-skills/manage-skills.component.html
src/app/resources/admin/manage-skills/manage-skills.component.ts
src/app/resources/organization/manage-candidates/manage-candidates.component.html
src/app/resources/organization/manage-candidates/manage-candidates.component.ts

added search for candidate table

added search for candidate table

---

db.json
src/app/commons/components/error-message/error-message.component.html
src/app/commons/utils/object-utils.ts
src/app/resources/admin/manage-skills/manage-skills.component.html
src/app/resources/admin/manage-skills/manage-skills.component.ts

manage skill changes

---

db.json
src/app/resources/admin/manage-skills/manage-skills.component.html
src/app/resources/admin/manage-skills/manage-skills.component.ts

skill changes

---

db.json
src/app/commons/components/carousel/carousel.component.ts
src/app/commons/constants/api-urls.ts
src/app/resources/organization/dashboard-organization/dashboard-organization.component.html
src/app/resources/organization/manage-hr-team/manage-hr-team.component.html
src/app/resources/organization/manage-hr-team/manage-hr-team.component.ts
src/app/resources/organization/manage-hr-team/manage-hr-team/manage-hr-team.service.spec.ts
src/app/resources/organization/manage-hr-team/manage-hr-team/manage-hr-team.service.ts
src/app/resources/organization/organization-routing.module.ts

team members changes

---

db.json
src/app/commons/components/candidate-queue/candidate-queue.component.html
src/app/commons/components/candidate-queue/candidate-queue.component.ts
src/app/commons/components/carousel/carousel.component.ts
src/app/resources/organization/manage-events/manage-events.component.ts
src/app/resources/organization/on-going-event-organization/on-going-event-organization.component.html
src/app/resources/organization/on-going-event-organization/on-going-event-organization.component.ts

dynamic carousel made

---

comming-soon.txt
db.json
src/app/commons/components/candidate-queue/candidate-queue.component.html
src/app/commons/components/candidate-queue/candidate-queue.component.ts
src/app/resources/organization/manage-candidates/manage-candidates.component.ts

changes for the candidate filter in on going event

changes for the candidate filter in on going event

---

src/app/resources/organization/dashboard-organization/dashboard-organization.component.html
src/app/resources/organization/manage-events/manage-events.component.html
src/app/resources/organization/manage-events/manage-events.component.scss
src/app/resources/organization/manage-hr-team/manage-hr-team.component.html
src/app/resources/organization/manage-hr-team/manage-hr-team.component.scss

added team fields

---

src/app/commons/components/profile/profile.component.ts
src/app/commons/constants/api-urls.ts
src/app/commons/services/local-storage/local-storage.service.ts
src/app/resources/admin/manage-skills/manage-skills.component.html
src/app/resources/admin/manage-skills/manage-skills.component.ts
src/app/resources/admin/manage-skills/manage-skills/manage-skills.service.ts
src/app/resources/individual/registration-individual/registration-individual.component.ts

skill integration done

---

src/app/resources/organization/manage-events/manage-events.component.html
src/app/resources/organization/manage-events/manage-events.component.scss
src/app/resources/organization/manage-events/manage-events.component.ts

round names detials added

---

db.json
src/app/resources/organization/manage-hr-team/manage-hr-team.component.html

manage team changes

---

db.json
src/app/resources/organization/manage-events/manage-events.component.html
src/app/resources/organization/manage-events/manage-events.component.ts

label changes

---

package-lock.json
package.json
src/app/commons/constants/shared.constants.ts
src/app/commons/typings/typings.ts
src/app/resources/organization/manage-events/manage-events.component.ts

skill detail update changes

---

src/app/commons/components/login-form/login-form/login-form.service.ts
src/app/commons/constants/api-urls.ts
src/app/resources/individual/registration-individual/registration-individual.component.html
src/app/resources/individual/registration-individual/registration-individual.component.ts
src/app/resources/organization/manage-events/manage-events.component.html
src/app/resources/organization/manage-events/manage-events.component.ts
src/app/resources/organization/registration-organization/registration-organization.component.ts

organization registration and login

organization registration and login

---

src/app/resources/individual/individual-routing.module.ts
src/app/resources/individual/registration-individual/registration-individual.component.ts
src/app/resources/individual/registration-individual/registration-individual/registration-individual.service.spec.ts
src/app/resources/individual/registration-individual/registration-individual/registration-individual.service.ts
src/app/resources/organization/manage-hr-team/manage-hr-team.component.html
src/app/resources/organization/manage-hr-team/manage-hr-team.component.ts
src/app/resources/organization/organization-routing.module.ts
src/app/resources/organization/registration-organization/registration-organization.component.ts
src/app/resources/organization/registration-organization/registration-organization/registration-organization.service.spec.ts
src/app/resources/organization/registration-organization/registration-organization/registration-organization.service.ts

registration services seperated

registration services seperated

---

src/app/commons/components/change-password/change-password.component.css
src/app/commons/components/change-password/change-password.component.html
src/app/commons/components/change-password/change-password.component.ts
src/app/commons/components/change-password/change-password/change-password.service.spec.ts
src/app/commons/components/change-password/change-password/change-password.service.ts
src/app/commons/components/components.module.ts
src/app/commons/components/header/header.component.ts
src/app/commons/typings/typings.ts
src/app/commons/utils/object-utils.ts

change password html created

---

comming-soon.txt
src/app/commons/components/header/header.component.html
src/app/commons/components/header/header.component.ts

on logo click navigation

---

comming-soon.txt
src/app/commons/components/change-password/change-password.component.ts
src/app/commons/components/change-password/change-password/change-password.service.ts
src/app/commons/constants/api-urls.ts
src/app/resources/individual/registration-individual/registration-individual.component.ts

individual registration

---

package-lock.json
package.json
src/app/app.component.html
src/app/app.component.ts
src/app/commons/components/alerts/alerts.component.html
src/app/commons/components/alerts/alerts.component.ts
src/app/commons/components/candidate-queue/candidate-queue.component.html
src/app/commons/components/candidate-queue/candidate-queue.component.ts
src/app/commons/components/carousel/carousel.component.ts
src/app/commons/components/change-password/change-password.component.ts
src/app/commons/components/error-message/error-message.component.html
src/app/commons/components/login-form/login-form.component.ts
src/app/commons/constants/shared.constants.ts
src/app/commons/services/alert/alert.service.ts
src/app/commons/utils/object-utils.ts
src/app/resources/admin/manage-skills/manage-skills.component.html
src/app/resources/admin/manage-skills/manage-skills.component.ts
src/app/resources/individual/registration-individual/registration-individual.component.ts
src/app/resources/main-screen/main-screen.component.html
src/app/resources/main-screen/main-screen.component.ts
src/app/resources/organization/edit-profile-organization/edit-profile-organization.component.ts
src/app/resources/organization/manage-candidates/manage-candidates.component.ts
src/app/resources/organization/manage-events/manage-events.component.html
src/app/resources/organization/manage-events/manage-events.component.ts
src/app/resources/organization/manage-hr-team/manage-hr-team.component.html
src/app/resources/organization/manage-hr-team/manage-hr-team.component.ts
src/app/resources/organization/on-going-event-organization/on-going-event-organization.component.ts
src/app/resources/organization/registration-organization/registration-organization.component.ts

alert changes

---

comming-soon.txt
src/app/commons/components/candidate-queue/candidate-queue.component.ts
src/app/commons/components/change-password/change-password.component.ts
src/app/commons/components/contact-us/contact-us.component.html
src/app/commons/components/login-form/login-form.component.html
src/app/commons/components/login-form/login-form.component.ts
src/app/commons/constants/api-urls.ts
src/app/commons/utils/object-utils.ts
src/app/resources/individual/registration-individual/registration-individual.component.ts
src/app/resources/main-screen/main-screen.component.ts
src/app/resources/organization/manage-events/manage-events.component.html
src/app/resources/organization/manage-events/manage-events.component.ts
src/app/resources/organization/manage-events/manage-events/manage-events.service.ts
src/app/resources/organization/manage-hr-team/manage-hr-team.component.html
src/app/resources/organization/manage-hr-team/manage-hr-team.component.ts
src/app/resources/organization/registration-organization/registration-organization.component.ts

individual login and event get done

individual login and event get done

---

src/app/app-routing.module.ts
src/app/app.component.ts
src/app/commons/components/autocomplete/skills-autocomplete/skills-autocomplete.component.html
src/app/commons/components/autocomplete/skills-autocomplete/skills-autocomplete.component.ts
src/app/commons/components/profile/profile.component.html
src/app/commons/components/profile/profile.component.ts
src/app/commons/constants/route-url-path.constants.ts
src/app/resources/individual/edit-profile-individual/edit-profile-individual.component.html
src/app/resources/individual/edit-profile-individual/edit-profile-individual.component.ts

skill autocomplete and edit individual profile changes

skill autocomplete and edit individual profile changes

---

src/app/commons/components/login-form/login-form.component.ts
src/app/resources/individual/edit-profile-individual/edit-profile-individual.component.ts
src/app/resources/individual/registration-individual/registration-individual.component.html
src/app/resources/individual/registration-individual/registration-individual.component.ts
src/app/resources/individual/registration-individual/registration-individual/registration-individual.service.ts
src/app/resources/main-screen/main-screen.component.html
src/app/resources/main-screen/main-screen.component.ts
src/app/resources/qa/qa-dashboard/qa-dashboard.component.html

standard changes

---

src/app/resources/organization/manage-candidates/manage-candidates.component.html
src/app/resources/organization/manage-candidates/manage-candidates.component.ts
src/app/resources/organization/manage-candidates/manage-candidates/manage-candidate.service.ts
src/app/resources/organization/manage-events/manage-events.component.html
src/app/resources/organization/manage-events/manage-events.component.ts
src/app/resources/organization/manage-events/manage-events/manage-events.service.ts
src/app/resources/organization/manage-hr-team/manage-hr-team.component.html
src/app/resources/organization/manage-hr-team/manage-hr-team.component.ts
src/app/resources/organization/manage-hr-team/manage-hr-team/manage-hr-team.service.ts
src/app/resources/organization/on-going-event-organization/on-going-event-organization.component.ts
src/app/resources/organization/registration-organization/registration-organization.component.html
src/app/resources/organization/registration-organization/registration-organization.component.ts
src/app/resources/organization/registration-organization/registration-organization/registration-organization.service.ts

Candidate registration

---

src/app/commons/components/loading-spinner/loading-spinner.component.html
src/sass/_common.scss

loader chagnes

---

src/app/app-routing.module.ts
src/app/commons/components/profile/profile.component.ts
src/app/commons/constants/api-urls.ts
src/app/resources/organization/manage-events/manage-events.component.ts
src/app/resources/organization/manage-events/manage-events/manage-events.service.ts
src/app/resources/organization/manage-hr-team/manage-hr-team.component.html
src/app/resources/organization/manage-hr-team/manage-hr-team.component.ts
src/app/resources/organization/manage-hr-team/manage-hr-team/manage-hr-team.service.ts

get team members integrated

---

src/app/commons/constants/api-urls.ts
src/app/resources/organization/manage-events/manage-events.component.ts
src/app/resources/organization/manage-events/manage-events/manage-events.service.ts
src/app/resources/organization/manage-hr-team/manage-hr-team/manage-hr-team.service.ts

manage event changes

---

src/app/commons/components/login-form/login-form.component.ts
src/app/commons/constants/api-urls.ts
src/app/resources/organization/manage-candidates/manage-candidates.component.html
src/app/resources/organization/manage-candidates/manage-candidates.component.ts
src/app/resources/organization/manage-events/manage-events.component.ts
src/app/resources/organization/manage-events/manage-events/manage-events.service.ts
src/app/resources/organization/registration-organization/registration-organization.component.ts

events integration

---

src/app/app.module.ts
src/app/commons/commons.module.ts
src/app/commons/components/autocomplete/email-autocomplete/email-autocomplete.component.css
src/app/commons/components/autocomplete/email-autocomplete/email-autocomplete.component.html
src/app/commons/components/autocomplete/email-autocomplete/email-autocomplete.component.spec.ts
src/app/commons/components/autocomplete/email-autocomplete/email-autocomplete.component.ts
src/app/commons/components/autocomplete/email-autocomplete/email-autocomplete/email-autocomplete.service.spec.ts
src/app/commons/components/autocomplete/email-autocomplete/email-autocomplete/email-autocomplete.service.ts
src/app/commons/components/components.module.ts
src/app/commons/components/modals/confirm-popup/confirm-popup.component.html
src/app/commons/components/modals/confirm-popup/confirm-popup.component.ts
src/app/commons/constants/api-urls.ts
src/app/commons/material-components/material-components.module.ts
src/app/resources/organization/edit-profile-organization/edit-profile-organization/edit-profile-organization.service.ts
src/app/resources/organization/manage-candidates/manage-candidates.component.html
src/app/resources/organization/manage-candidates/manage-candidates.component.ts
src/app/resources/organization/manage-candidates/manage-candidates/manage-candidate.service.ts
src/app/resources/organization/manage-events/manage-events.component.ts
src/app/resources/organization/manage-events/manage-events/manage-events.service.ts
src/app/resources/organization/manage-hr-team/manage-hr-team.component.html
src/app/resources/organization/manage-hr-team/manage-hr-team.component.ts
src/app/resources/organization/manage-hr-team/manage-hr-team/manage-hr-team.service.ts
src/sass/_common.scss

event integration changes

---

comming-soon.txt
src/app/commons/components/login-form/login-form.component.ts
src/app/commons/constants/api-urls.ts
src/app/resources/individual/edit-profile-individual/edit-profile-individual.component.ts
src/app/resources/individual/edit-profile-individual/edit-profile-individual/edit-profile-individual.service.spec.ts
src/app/resources/individual/edit-profile-individual/edit-profile-individual/edit-profile-individual.service.ts
src/app/resources/individual/individual-routing.module.ts
src/app/resources/individual/individual.module.ts
src/app/resources/individual/registration-individual/registration-individual.component.ts
src/app/resources/organization/edit-profile-organization/edit-profile-organization.component.html
src/app/resources/organization/edit-profile-organization/edit-profile-organization.component.ts
src/app/resources/organization/manage-candidates/manage-candidates.component.html
src/app/resources/organization/manage-candidates/manage-candidates.component.ts
src/app/resources/organization/manage-candidates/manage-candidates/manage-candidate.service.ts
src/app/resources/organization/registration-organization/registration-organization.component.ts

integration of edit and update profile

integration of edit and update profile

---

src/app/commons/components/about-us/about-us.component.html
src/app/commons/components/autocomplete/email-autocomplete/email-autocomplete.component.ts
src/app/commons/constants/api-urls.ts
src/app/commons/typings/typings.ts
src/app/commons/utils/object-utils.ts
src/app/resources/individual/edit-profile-individual/edit-profile-individual.component.html
src/app/resources/individual/edit-profile-individual/edit-profile-individual.component.ts
src/app/resources/individual/registration-individual/registration-individual.component.html
src/app/resources/individual/registration-individual/registration-individual.component.ts
src/app/resources/organization/edit-profile-organization/edit-profile-organization.component.html
src/app/resources/organization/edit-profile-organization/edit-profile-organization.component.ts
src/app/resources/organization/manage-candidates/manage-candidates.component.html
src/app/resources/organization/manage-candidates/manage-candidates.component.ts
src/app/resources/organization/manage-candidates/manage-candidates/manage-candidate.service.ts
src/app/resources/organization/manage-events/manage-events.component.html

issue fixes

---

src/app/app-routing.module.ts
src/app/commons/components/login-form/login-form.component.ts
src/app/commons/components/profile/profile.component.ts
src/app/commons/constants/api-urls.ts
src/app/commons/rest-services/shared/shared.service.ts
src/app/commons/services/services.module.ts
src/app/commons/services/user-details-resolver/user-details-resolver.service.spec.ts
src/app/commons/services/user-details-resolver/user-details-resolver.service.ts
src/app/commons/utils/object-utils.ts
src/app/resources/individual/registration-individual/registration-individual.component.ts
src/app/resources/individual/registration-individual/registration-individual/registration-individual.service.ts
src/app/resources/main-screen/main-screen.component.ts
src/app/resources/organization/edit-profile-organization/edit-profile-organization.component.html
src/app/resources/organization/edit-profile-organization/edit-profile-organization.component.ts
src/app/resources/organization/manage-events/manage-events.component.ts
src/app/resources/organization/manage-hr-team/manage-hr-team.component.ts
src/app/resources/organization/registration-organization/registration-organization.component.ts
src/app/resources/organization/registration-organization/registration-organization/registration-organization.service.ts

new structure changes

---

src/app/app.component.ts
src/app/commons/components/login-form/login-form.component.ts
src/app/commons/constants/api-urls.ts
src/app/commons/constants/shared.constants.ts
src/app/commons/rest-services/shared/shared.service.ts
src/app/commons/services/user-details-resolver/user-details-resolver.service.ts
src/app/commons/utils/object-utils.ts
src/app/resources/individual/registration-individual/registration-individual.component.ts
src/app/resources/organization/edit-profile-organization/edit-profile-organization.component.ts
src/app/resources/organization/edit-profile-organization/edit-profile-organization/edit-profile-organization.service.ts
src/app/resources/organization/manage-hr-team/manage-hr-team.component.ts
src/app/resources/organization/organization.module.ts
src/app/resources/organization/registration-organization/registration-organization.component.ts

login and registration changes

login and registration changes

---

src/app/commons/components/autocomplete/email-autocomplete/email-autocomplete.component.ts
src/app/commons/components/change-password/change-password.component.ts
src/app/commons/components/login-form/login-form.component.ts
src/app/commons/components/time-input-field/time-input-field.component.ts
src/app/commons/services/loading-interceptor/loading-interceptor.service.ts
src/app/resources/admin/manage-skills/manage-skills.component.ts
src/app/resources/individual/edit-profile-individual/edit-profile-individual.component.ts
src/app/resources/individual/edit-profile-individual/edit-profile-individual/edit-profile-individual.service.ts
src/app/resources/individual/registration-individual/registration-individual.component.ts
src/app/resources/organization/edit-profile-organization/edit-profile-organization.component.ts
src/app/resources/organization/manage-candidates/manage-candidates.component.ts
src/app/resources/organization/manage-hr-team/manage-hr-team.component.ts
src/app/resources/organization/on-going-event-organization/on-going-event-organization.component.ts
src/app/resources/organization/registration-organization/registration-organization.component.ts

serice url changes

---

comming-soon.txt
src/app/commons/components/profile/profile.component.ts
src/app/commons/constants/api-urls.ts
src/app/commons/utils/helper-util.ts
src/app/resources/organization/manage-candidates/manage-candidates.component.ts
src/app/resources/organization/manage-hr-team/manage-hr-team.component.html
src/app/resources/organization/manage-hr-team/manage-hr-team.component.ts
src/app/resources/organization/manage-hr-team/manage-hr-team/manage-hr-team.service.ts

intergration changes

---

src/app/commons/utils/object-utils.ts
src/app/resources/organization/manage-candidates/manage-candidates.component.ts
src/app/resources/organization/manage-events/manage-events.component.ts
src/app/resources/organization/manage-hr-team/manage-hr-team.component.html
src/app/resources/organization/manage-hr-team/manage-hr-team.component.ts

event changes

---

src/app/commons/constants/api-urls.ts
src/app/resources/individual/registration-individual/registration-individual.component.html
src/app/resources/organization/edit-profile-hr/edit-profile-hr.component.html
src/app/resources/organization/edit-profile-hr/edit-profile-hr.component.ts
src/app/resources/organization/edit-profile-organization/edit-profile-organization.component.html
src/app/resources/organization/edit-profile-organization/edit-profile-organization.component.ts
src/app/resources/organization/manage-candidates/manage-candidates.component.ts
src/app/resources/organization/manage-events/manage-events.component.ts
src/app/resources/organization/manage-hr-team/manage-hr-team.component.html
src/app/resources/organization/manage-hr-team/manage-hr-team.component.ts
src/app/resources/organization/registration-organization/registration-organization.component.html

integration changes

---

src/app/app-routing.module.ts
src/app/resources/organization/edit-profile-organization/edit-profile-organization.component.html
src/app/resources/organization/edit-profile-organization/edit-profile-organization.component.ts
src/app/resources/organization/edit-profile-organization/edit-profile-organization/edit-profile-organization.service.ts

organization profiles changes

---

src/app/resources/organization/manage-events/manage-events.component.html
src/app/resources/organization/manage-events/manage-events.component.scss
src/app/resources/organization/manage-events/manage-events.component.ts

round details required changes

round details required changes

---

src/app/commons/components/candidate-queue/candidate-queue.component.html
src/app/commons/components/candidate-queue/candidate-queue.component.ts
src/app/commons/components/no-records-found/no-records-found.component.html
src/app/resources/individual/dashboard-individual/dashboard-individual.component.html
src/app/resources/individual/dashboard-individual/dashboard-individual.component.ts
src/app/resources/organization/manage-candidates/manage-candidates.component.html
src/app/resources/organization/manage-candidates/manage-candidates.component.ts
src/app/resources/organization/manage-events/manage-events.component.html
src/app/resources/organization/manage-events/manage-events.component.ts
src/app/resources/organization/manage-hr-team/manage-hr-team.component.html

individual dashboard changes

---

src/app/commons/components/login-logo-slider/login-logo-slider.component.html
src/app/commons/constants/api-urls.ts
src/app/resources/individual/registration-individual/registration-individual.component.html
src/app/resources/individual/registration-individual/registration-individual.component.ts
src/app/resources/main-screen/main-screen.component.html
src/app/resources/main-screen/main-screen.component.ts

mobile view changes

---

comming-soon.txt
package.json
src/app/commons/components/autocomplete/email-autocomplete/email-autocomplete.component.html
src/app/commons/components/autocomplete/email-autocomplete/email-autocomplete.component.ts
src/app/commons/components/autocomplete/skills-autocomplete/skills-autocomplete.component.html
src/app/commons/components/change-password/change-password.component.html
src/app/resources/individual/edit-profile-individual/edit-profile-individual.component.html
src/app/resources/individual/edit-profile-individual/edit-profile-individual.component.ts
src/app/resources/organization/edit-profile-hr/edit-profile-hr.component.html
src/app/resources/organization/edit-profile-organization/edit-profile-organization.component.html
src/app/resources/organization/manage-candidates/manage-candidates.component.html
src/app/resources/organization/manage-candidates/manage-candidates.component.ts
src/app/resources/organization/manage-events/manage-events.component.html
src/app/resources/organization/manage-events/manage-events.component.ts
src/app/resources/organization/manage-hr-team/manage-hr-team.component.html
src/app/resources/organization/manage-hr-team/manage-hr-team.component.ts

placeholder changes

---

src/app/commons/components/autocomplete/skills-autocomplete/skills-autocomplete.component.html
src/app/resources/individual/edit-profile-individual/edit-profile-individual.component.html
src/app/resources/organization/manage-candidates/manage-candidates.component.ts

candidate changes

---

src/app/resources/organization/manage-events/manage-events.component.html
src/app/resources/organization/manage-events/manage-events.component.ts

event related changes

---

comming-soon.txt
src/app/resources/organization/manage-candidates/manage-candidates.component.html
src/app/resources/organization/manage-events/manage-events.component.html
src/app/resources/organization/manage-events/manage-events.component.ts

event update fix

---

src/app/commons/components/components.module.ts
src/app/commons/components/snack-bar-alert/snack-bar-alert.component.html
src/app/commons/components/snack-bar-alert/snack-bar-alert.component.spec.ts
src/app/commons/components/snack-bar-alert/snack-bar-alert.component.ts

snackbar component
